#!/usr/bin/env python
"""
    MoinMoin CLI interface - not working yet!

"""

import sys
sys.path.insert(0, '/home/twaldmann/moincvs/moin--main')
sys.path.insert(0, '/org/wiki')
sys.path.insert(0, '/org/org.linuxwiki/cgi-bin')

from MoinMoin.request import RequestCLI

def run():
    page = sys.argv[1]
    req = RequestCLI(page)
    req.run()

