#!/usr/bin/env python
"""
moin - control MoinMoin Standalone server

@copyright: 2004-2005 Thomas Waldmann, Nir Soffer
@license: GNU GPL, see COPYING for details.
"""

# Add the path to moin.py directory 
## import sys
## sys.path.insert(0, '/path/to/moin')

from MoinMoin.server import daemon
from moin import Config, run

script = daemon.DaemonScript(Config.name, run, Config)
script.run()
